# Generated by Django 5.0.6 on 2024-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
