# Generated by Django 5.0.6 on 2024-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0002_size_quantity_in_stock_delete_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='title',
        ),
    ]
