# Generated by Django 5.0.6 on 2024-06-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0003_color_size_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='image_url',
            field=models.URLField(max_length=100),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InviteFashionAPI.color')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InviteFashionAPI.productitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InviteFashionAPI.size')),
            ],
        ),
    ]
