# Generated by Django 5.0.6 on 2024-06-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0004_alter_productitem_image_url_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='quantity_in_stock',
        ),
    ]
