# Generated by Django 5.0.6 on 2024-06-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0006_alter_productitem_porduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='porduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InviteFashionAPI.product'),
        ),
    ]
