# Generated by Django 5.0.6 on 2024-06-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0008_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='porduct',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='InviteFashionAPI.category'),
        ),
    ]
