# Generated by Django 5.0.6 on 2024-06-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0009_rename_porduct_productitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='InviteFashionAPI.productitem'),
        ),
    ]
