# Generated by Django 5.0.6 on 2024-06-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InviteFashionAPI', '0010_alter_variant_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
    ]
